"""initial schema

Revision ID: 5d3a712b3ced
Revises: 
Create Date: 2026-02-10 00:26:50.712871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d3a712b3ced'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_study_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('syllabus_file', sa.String(), nullable=True),
    sa.Column('plan_type', sa.String(), nullable=False),
    sa.Column('timeline', sa.JSON(), nullable=False),
    sa.Column('exam_dates', sa.JSON(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('total_weeks', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('goal_type', sa.String(), nullable=True),
    sa.Column('custom_goals', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_execution_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('execution_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(length=20), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('action_data', sa.JSON(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('current_state', sa.JSON(), nullable=False),
    sa.Column('pending_tasks', sa.JSON(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('agent_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anesthesia_care_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('procedure', sa.String(length=500), nullable=False),
    sa.Column('diagnosis', sa.String(length=500), nullable=True),
    sa.Column('plan_data', sa.JSON(), nullable=False),
    sa.Column('patient_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('modality', sa.String(length=50), nullable=False),
    sa.Column('content_url', sa.String(), nullable=True),
    sa.Column('content_blob', sa.String(), nullable=True),
    sa.Column('artifact_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('scheduled_review', sa.DateTime(), nullable=True),
    sa.Column('retention_score', sa.DECIMAL(), nullable=True),
    sa.Column('times_reviewed', sa.Integer(), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.Column('quality', sa.DECIMAL(), nullable=True),
    sa.Column('generated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('behavioral_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analysis_data', sa.JSON(), nullable=False),
    sa.Column('interventions', sa.JSON(), nullable=True),
    sa.Column('engagement_level', sa.DECIMAL(), nullable=True),
    sa.Column('knowledge_decay_risk', sa.DECIMAL(), nullable=True),
    sa.Column('average_performance', sa.DECIMAL(), nullable=True),
    sa.Column('stress_level', sa.DECIMAL(), nullable=True),
    sa.Column('generated_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biometric_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('heart_rate_variability', sa.DECIMAL(), nullable=True),
    sa.Column('sleep_score', sa.DECIMAL(), nullable=True),
    sa.Column('resting_heart_rate', sa.Integer(), nullable=True),
    sa.Column('activity_level', sa.DECIMAL(), nullable=True),
    sa.Column('stress_level', sa.DECIMAL(), nullable=True),
    sa.Column('readiness_score', sa.DECIMAL(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biometric_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('connected', sa.Boolean(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('sync_frequency', sa.Integer(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('board_exam_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('exam_type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('topic_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('inquiry_type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_generation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('board_topic_id', sa.Integer(), nullable=True),
    sa.Column('generation_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('generated_content', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics_data',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('metric_unit', sa.String(length=20), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dashboard'
    )
    op.create_table('dashboard_layouts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('layout_name', sa.String(length=100), nullable=False),
    sa.Column('layout_config', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dashboard'
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('date_format', sa.String(length=20), nullable=True),
    sa.Column('dashboard_settings', sa.JSON(), nullable=True),
    sa.Column('notification_settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='dashboard'
    )
    op.create_table('user_widgets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dashboard_layout_id', sa.UUID(), nullable=True),
    sa.Column('widget_id', sa.UUID(), nullable=True),
    sa.Column('widget_position', sa.JSON(), nullable=False),
    sa.Column('widget_settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dashboard'
    )
    op.create_table('widgets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('widget_type', sa.String(length=50), nullable=False),
    sa.Column('widget_name', sa.String(length=100), nullable=False),
    sa.Column('widget_config', sa.JSON(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dashboard'
    )
    op.create_table('federation_updates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subnet_id', sa.String(length=100), nullable=False),
    sa.Column('update_data', sa.JSON(), nullable=False),
    sa.Column('update_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('aggregated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vark_style', sa.String(length=20), nullable=False),
    sa.Column('preferred_study_duration', sa.Integer(), nullable=True),
    sa.Column('best_study_times', sa.JSON(), nullable=True),
    sa.Column('difficulty_preference', sa.String(length=20), nullable=True),
    sa.Column('content_types', sa.JSON(), nullable=True),
    sa.Column('last_vark_assessment', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('times_accessed', sa.Integer(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('care_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=True),
    sa.Column('procedure', sa.String(length=500), nullable=True),
    sa.Column('diagnosis', sa.String(length=500), nullable=True),
    sa.Column('age', sa.String(length=50), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('height', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.String(length=50), nullable=True),
    sa.Column('temperature_f', sa.String(length=20), nullable=True),
    sa.Column('blood_pressure', sa.String(length=50), nullable=True),
    sa.Column('heart_rate', sa.String(length=20), nullable=True),
    sa.Column('respiration_rate', sa.String(length=20), nullable=True),
    sa.Column('oxygen_saturation', sa.String(length=20), nullable=True),
    sa.Column('lmp_date', sa.String(length=50), nullable=True),
    sa.Column('past_medical_history', sa.Text(), nullable=True),
    sa.Column('past_surgical_history', sa.Text(), nullable=True),
    sa.Column('anesthesia_history', sa.Text(), nullable=True),
    sa.Column('current_medications', sa.Text(), nullable=True),
    sa.Column('alcohol_use', sa.Text(), nullable=True),
    sa.Column('substance_use', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('neurological_findings', sa.Text(), nullable=True),
    sa.Column('heent_findings', sa.Text(), nullable=True),
    sa.Column('respiratory_findings', sa.Text(), nullable=True),
    sa.Column('cardiovascular_findings', sa.Text(), nullable=True),
    sa.Column('gastrointestinal_findings', sa.Text(), nullable=True),
    sa.Column('genitourinary_findings', sa.Text(), nullable=True),
    sa.Column('endocrine_findings', sa.Text(), nullable=True),
    sa.Column('other_findings', sa.Text(), nullable=True),
    sa.Column('mallampati_class', sa.String(length=50), nullable=True),
    sa.Column('ulbt_grade', sa.String(length=50), nullable=True),
    sa.Column('thyromental_distance', sa.String(length=20), nullable=True),
    sa.Column('interincisor_distance', sa.String(length=20), nullable=True),
    sa.Column('dentition', sa.Text(), nullable=True),
    sa.Column('neck_assessment', sa.Text(), nullable=True),
    sa.Column('oral_mucosa', sa.Text(), nullable=True),
    sa.Column('sodium', sa.String(length=20), nullable=True),
    sa.Column('potassium', sa.String(length=20), nullable=True),
    sa.Column('chloride', sa.String(length=20), nullable=True),
    sa.Column('co2', sa.String(length=20), nullable=True),
    sa.Column('bun', sa.String(length=20), nullable=True),
    sa.Column('creatinine', sa.String(length=20), nullable=True),
    sa.Column('glucose', sa.String(length=20), nullable=True),
    sa.Column('wbc', sa.String(length=20), nullable=True),
    sa.Column('hemoglobin', sa.String(length=20), nullable=True),
    sa.Column('hematocrit', sa.String(length=20), nullable=True),
    sa.Column('platelets', sa.String(length=20), nullable=True),
    sa.Column('pt', sa.String(length=20), nullable=True),
    sa.Column('ptt', sa.String(length=20), nullable=True),
    sa.Column('inr', sa.String(length=20), nullable=True),
    sa.Column('abg', sa.String(length=50), nullable=True),
    sa.Column('other_labs', sa.Text(), nullable=True),
    sa.Column('ekg', sa.Text(), nullable=True),
    sa.Column('chest_xray', sa.Text(), nullable=True),
    sa.Column('echocardiogram', sa.Text(), nullable=True),
    sa.Column('other_imaging', sa.Text(), nullable=True),
    sa.Column('cultural_religious_attributes', sa.Text(), nullable=True),
    sa.Column('ai_recommendations', sa.Text(), nullable=True),
    sa.Column('risk_assessment', sa.Text(), nullable=True),
    sa.Column('monitoring_plan', sa.Text(), nullable=True),
    sa.Column('medication_plan', sa.Text(), nullable=True),
    sa.Column('rag_context', sa.Text(), nullable=True),
    sa.Column('rag_sources', sa.JSON(), nullable=True),
    sa.Column('rag_confidence_score', sa.DECIMAL(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('exported_text', sa.Text(), nullable=True),
    sa.Column('export_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('lms_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('syllabus_html', sa.Text(), nullable=True),
    sa.Column('course_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('front', sa.String(), nullable=False),
    sa.Column('back', sa.String(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('memory_aid', sa.String(), nullable=True),
    sa.Column('learning_style', sa.String(length=20), nullable=True),
    sa.Column('times_reviewed', sa.Integer(), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.Column('next_review', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('learning_modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('learning_plan_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('learning_plan_id', sa.Integer(), nullable=False),
    sa.Column('video_watched', sa.Boolean(), nullable=True),
    sa.Column('video_watched_at', sa.DateTime(), nullable=True),
    sa.Column('video_progress', sa.Integer(), nullable=True),
    sa.Column('case_study_read', sa.Boolean(), nullable=True),
    sa.Column('case_study_read_at', sa.DateTime(), nullable=True),
    sa.Column('case_study_notes', sa.Text(), nullable=True),
    sa.Column('quiz_submitted', sa.Boolean(), nullable=True),
    sa.Column('quiz_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('quiz_answers', sa.JSON(), nullable=True),
    sa.Column('quiz_score', sa.Integer(), nullable=True),
    sa.Column('quiz_total', sa.Integer(), nullable=True),
    sa.Column('quiz_percentage', sa.Numeric(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('learning_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('video_title', sa.String(length=255), nullable=True),
    sa.Column('video_duration', sa.Integer(), nullable=True),
    sa.Column('case_study', sa.Text(), nullable=False),
    sa.Column('case_study_editable', sa.Boolean(), nullable=True),
    sa.Column('quiz_questions', sa.JSON(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('processing_progress', sa.Integer(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('grad_year', sa.String(), nullable=True),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('last_attempt_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('percentage_complete', sa.Integer(), nullable=True),
    sa.Column('last_studied', sa.DateTime(), nullable=True),
    sa.Column('decay_rate', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('profile_completed', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('requires_password_change', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='main'
    )
    op.create_table('mastery_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('mastery_level', sa.DECIMAL(), nullable=False),
    sa.Column('readiness_score', sa.DECIMAL(), nullable=False),
    sa.Column('last_assessed', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('assessment_count', sa.Integer(), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('mastery_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modality_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('modality', sa.String(length=50), nullable=False),
    sa.Column('preference_score', sa.DECIMAL(), nullable=False),
    sa.Column('success_rate', sa.DECIMAL(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('delivery_method', sa.String(length=30), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('redirect_uri', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state')
    )
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('encrypted_access_token', sa.String(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('token_metadata', sa.JSON(), nullable=True),
    sa.Column('last_refreshed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('plan_courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proactive_quizzes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('quiz_data', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('score', sa.DECIMAL(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('generated_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_retrieval_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('retrieved_docs', sa.JSON(), nullable=False),
    sa.Column('relevance_scores', sa.JSON(), nullable=False),
    sa.Column('iteration_count', sa.Integer(), nullable=True),
    sa.Column('final_response', sa.String(), nullable=True),
    sa.Column('response_quality', sa.DECIMAL(), nullable=True),
    sa.Column('execution_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('sid', sa.String(), nullable=False),
    sa.Column('sess', sa.JSON(), nullable=False),
    sa.Column('expire', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('study_activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_of', sa.DateTime(), nullable=False),
    sa.Column('plan_data', sa.JSON(), nullable=False),
    sa.Column('generated_by', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('message_content', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('message_length', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='user_data'
    )
    op.create_table('user_interactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('interaction_type', sa.String(), nullable=True),
    sa.Column('interaction_data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('page_url', sa.Text(), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='user_data'
    )
    op.create_table('user_session',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('session_duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='user_data'
    )
    op.create_table('vark_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('learning_style', sa.String(length=20), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('generated_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vector_index_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('vector_metadata', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_table('visual_guides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('svg_elements', sa.JSON(), nullable=True),
    sa.Column('interactive_elements', sa.JSON(), nullable=True),
    sa.Column('completion_status', sa.String(length=20), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('last_viewed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waitlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('weekly_insights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_starting', sa.DateTime(), nullable=False),
    sa.Column('week_ending', sa.DateTime(), nullable=False),
    sa.Column('total_study_time', sa.Integer(), nullable=False),
    sa.Column('daily_average', sa.Integer(), nullable=False),
    sa.Column('overall_retention', sa.Integer(), nullable=False),
    sa.Column('strongest_topics', sa.JSON(), nullable=False),
    sa.Column('weakest_topics', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('daily_activity', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_insights')
    op.drop_table('waitlist')
    op.drop_table('visual_guides')
    op.drop_table('vector_index_entries')
    op.drop_table('vark_content')
    op.drop_table('user_session', schema='user_data')
    op.drop_table('user_interactions', schema='user_data')
    op.drop_table('chat_messages', schema='user_data')
    op.drop_table('test_results')
    op.drop_table('study_plans')
    op.drop_table('study_activity')
    op.drop_table('sessions')
    op.drop_table('rag_retrieval_logs')
    op.drop_table('proactive_quizzes')
    op.drop_table('plan_courses')
    op.drop_table('password_resets')
    op.drop_table('oauth_tokens')
    op.drop_table('oauth_states')
    op.drop_table('notification_queue')
    op.drop_table('modality_preferences')
    op.drop_table('mastery_scores')
    op.drop_table('users', schema='main')
    op.drop_table('topics', schema='main')
    op.drop_table('tests', schema='main')
    op.drop_table('profiles', schema='main')
    op.drop_table('materials', schema='main')
    op.drop_table('learning_plans', schema='main')
    op.drop_table('learning_plan_progress', schema='main')
    op.drop_table('learning_modules', schema='main')
    op.drop_table('flashcards', schema='main')
    op.drop_table('courses', schema='main')
    op.drop_table('care_plans', schema='main')
    op.drop_table('library_content')
    op.drop_table('learning_preferences')
    op.drop_table('federation_updates')
    op.drop_table('widgets', schema='dashboard')
    op.drop_table('user_widgets', schema='dashboard')
    op.drop_table('user_preferences', schema='dashboard')
    op.drop_table('dashboard_layouts', schema='dashboard')
    op.drop_table('analytics_data', schema='dashboard')
    op.drop_table('course_items')
    op.drop_table('content_generation')
    op.drop_table('contact_messages')
    op.drop_table('board_exam_topics')
    op.drop_table('biometric_devices')
    op.drop_table('biometric_data')
    op.drop_table('behavioral_analysis')
    op.drop_table('artifacts')
    op.drop_table('anesthesia_care_plans')
    op.drop_table('agent_states')
    op.drop_table('agent_notifications')
    op.drop_table('agent_execution_logs')
    op.drop_table('academic_study_plans')
    # ### end Alembic commands ###
